### PR TITLE
Add more functionality 

### PR DESCRIPTION
**Pull request by shortdudey123**
- update Ruby syntax for passing tests
- Add option for passphrase on user keys
- Generate tls-auth key for server when server create is used
- Generate a server type cert for server create
- Don't miss config details if they are default and not specified on the server attribute
- Export tls-auth key

### CODE REVIEW

**Comment by shortdudey123** [comment]
@ikurochkin can you take a look at this when you have a chance and let me know what you think

**Comment by ikurochkin** [comment]
@shortdudey123 will do it asap, thanks!

**Comment by shortdudey123** [comment]
Need to yank out the ta key generation since that part isn't working.  Will do it another way in the openvpn cookbook

**Comment by shortdudey123** [comment]
Good to go now

**Comment by whitew1nd** [comment]
Thanks, @shortdudey123 !

**Pull request merged**
